'use client'

import { useState, useEffect } from 'react'
import { X, Loader2, Bug } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { bugsApi } from '@/lib/api/bugs.api'
import { projectsApi } from '@/lib/api/projects.api'
import { usersApi } from '@/lib/api/users.api'
import { tasksApi } from '@/lib/api/tasks.api'
import { useAuthStore } from '@/store/auth.store'
import {
  BUG_SEVERITIES, BUG_SEVERITY_LABELS,
  BUG_PRIORITIES, BUG_PRIORITY_LABELS,
  BUG_ENVIRONMENTS, BUG_ENVIRONMENT_LABELS,
} from '@/constants/bugs'
import { MAX_FILE_SIZE } from '@/constants'

const SELECT =
  'w-full px-3 py-2 text-sm border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-violet-500 bg-card'

/**
 * Report a bug (§11).
 *
 * Reporter comes from the authenticated session and the bug ID is generated by
 * the database, so neither is a form field. Attachments are uploaded AFTER the
 * bug exists — the attachment endpoint is scoped to a bug id, and a failed
 * upload must not lose the report itself.
 */
export function CreateBugModal({ onClose, onSuccess, defaultProjectId = '' }) {
  const { user } = useAuthStore()
  // Only admin/manager can open this modal at all (the Report Bug button is
  // gated), so assignment is always available. Kept as a named check rather
  // than hardcoded true so the guard stays visible if that ever changes.
  const canAssign = ['admin', 'qc'].includes(user?.role)

  const [form, setForm] = useState({
    title: '',
    description: '',
    stepsToReproduce: '',
    projectId: defaultProjectId,
    severity: 'medium',
    priority: 'p2',
    environment: 'production',
    assigneeId: '',
    linkedTaskId: '',
  })
  const [files, setFiles] = useState([])
  const [isLoading, setIsLoading] = useState(false)
  const [errors, setErrors] = useState({})
  // Set while attachments upload after the bug row is created, so the button
  // can say what it is actually doing rather than just "Creating...".
  const [uploadPhase, setUploadPhase] = useState(null)

  const [projects, setProjects] = useState([])
  const [users, setUsers] = useState([])
  const [tasks, setTasks] = useState([])
  const [slaRules, setSlaRules] = useState([])
  const [lookupError, setLookupError] = useState(false)

  async function loadLookups() {
    setLookupError(false)
    try {
      // Employees cannot read the full user list (GET /users is admin/manager
      // only), so only ask for what this role is allowed to have.
      const [projectRes, ruleRes, userRes] = await Promise.all([
        projectsApi.getAll().catch(() => []),
        bugsApi.getSlaRules().catch(() => []),
        canAssign ? usersApi.getAll().catch(() => []) : Promise.resolve([]),
      ])
      setProjects(Array.isArray(projectRes?.data ?? projectRes) ? projectRes?.data ?? projectRes : [])
      setUsers(Array.isArray(userRes?.data ?? userRes) ? userRes?.data ?? userRes : [])
      setSlaRules(Array.isArray(ruleRes) ? ruleRes : [])
    } catch {
      setLookupError(true)
    }
  }

  useEffect(() => {
    // loadLookups only calls setState after its internal await — the same
    // traced false positive this rule produces throughout the codebase (see
    // create-task-modal.jsx and use-has-mounted.js).
    // eslint-disable-next-line react-hooks/set-state-in-effect
    loadLookups()
    // Mount-only: the lookups do not change while the modal is open.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Linkable tasks are scoped to the chosen project AND to the chosen
  // developer: a bug is linked to the work that developer is already doing, so
  // offering tasks assigned to somebody else would only produce a mismatched
  // link. With no developer chosen there is nothing meaningful to offer yet.
  useEffect(() => {
    let active = true
    // The empty cases resolve through the same async path as a real fetch, so
    // this effect never calls setState synchronously in its body.
    const pending =
      form.projectId && form.assigneeId
        ? tasksApi
            .getByProject(form.projectId)
            .then((res) => (Array.isArray(res) ? res : res?.data || []))
            .then((list) => list.filter((t) => t.assignee?.id === form.assigneeId))
        : Promise.resolve([])

    pending
      .then((list) => {
        if (!active) return
        setTasks(list)
        // Drop a selection that the new project/developer no longer offers,
        // otherwise the form would submit a linkedTaskId belonging to someone
        // else's work while the dropdown appears to show "None".
        setForm((prev) =>
          prev.linkedTaskId && !list.some((t) => t.id === prev.linkedTaskId)
            ? { ...prev, linkedTaskId: '' }
            : prev
        )
      })
      .catch(() => { if (active) setTasks([]) })

    return () => { active = false }
  }, [form.projectId, form.assigneeId])

  function handleChange(e) {
    setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }))
    setErrors((prev) => ({ ...prev, [e.target.name]: '', general: '' }))
  }

  function handleFiles(e) {
    const picked = Array.from(e.target.files || [])
    const rejected = picked.filter((f) => f.size > MAX_FILE_SIZE)
    if (rejected.length) {
      setErrors((prev) => ({
        ...prev,
        files: `${rejected.map((f) => f.name).join(', ')} exceeds the 10MB limit.`,
      }))
    } else {
      setErrors((prev) => ({ ...prev, files: '' }))
    }
    setFiles(picked.filter((f) => f.size <= MAX_FILE_SIZE))
  }

  function validate() {
    const next = {}
    if (!form.title.trim()) next.title = 'Bug title is required.'
    else if (form.title.trim().length > 500) next.title = 'Title must be 500 characters or fewer.'
    if (!form.description.trim()) next.description = 'Description is required.'
    if (!form.projectId) next.projectId = 'Please select a project.'
    return next
  }

  async function handleSubmit(e) {
    e.preventDefault()
    const validationErrors = validate()
    if (Object.keys(validationErrors).length) {
      setErrors(validationErrors)
      return
    }

    setIsLoading(true)
    setErrors({})
    try {
      const bug = await bugsApi.create({
        title: form.title.trim(),
        description: form.description.trim(),
        stepsToReproduce: form.stepsToReproduce.trim() || null,
        projectId: form.projectId,
        severity: form.severity,
        priority: form.priority,
        environment: form.environment,
        // An employee never sees these controls; send them only when set.
        assigneeId: form.assigneeId || undefined,
        linkedTaskId: form.linkedTaskId || undefined,
      })

      // Attachments are best-effort: the bug is already filed, so a storage
      // failure is reported as a warning rather than discarding the report.
      const failed = []
      for (let i = 0; i < files.length; i += 1) {
        setUploadPhase(`Uploading ${i + 1} of ${files.length}...`)
        const formData = new FormData()
        formData.append('file', files[i])
        try {
          await bugsApi.uploadAttachment(bug.id, formData)
        } catch {
          failed.push(files[i].name)
        }
      }

      onSuccess?.(bug, { failedAttachments: failed })
      onClose()
    } catch (err) {
      setErrors({
        general:
          err.response?.data?.message ||
          'Failed to report the bug. Please check your connection and try again.',
      })
    } finally {
      setIsLoading(false)
      setUploadPhase(null)
    }
  }

  // Show the SLA the chosen severity will apply, so the reporter sees the
  // commitment they are creating before they create it.
  const activeRule = slaRules.find((r) => r.severity === form.severity)
  const formatMinutes = (m) => {
    if (!m) return '—'
    if (m < 60) return `${m}m`
    if (m < 60 * 24) return `${Math.round((m / 60) * 10) / 10}h`
    return `${Math.round((m / 480) * 10) / 10} business days`
  }

  return (
    <div
      className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
      onClick={(e) => e.target === e.currentTarget && !isLoading && onClose()}
    >
      <div className="bg-card rounded-2xl w-full max-w-2xl shadow-xl max-h-[90vh] overflow-y-auto">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border sticky top-0 bg-card rounded-t-2xl z-10">
          <h2 className="text-base font-semibold text-foreground inline-flex items-center gap-2">
            <Bug className="w-4 h-4 text-red-500" />
            Report a Bug
          </h2>
          <button
            type="button"
            onClick={onClose}
            disabled={isLoading}
            className="text-slate-400 hover:text-muted-foreground p-1 rounded-lg hover:bg-background disabled:opacity-50"
            aria-label="Close"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="px-6 py-5 space-y-4">

          {errors.general && (
            <div className="bg-red-50 border border-red-200 text-red-600 text-sm rounded-lg px-4 py-3">
              {errors.general}
            </div>
          )}
          {lookupError && (
            <div className="bg-amber-50 border border-amber-200 text-amber-700 text-sm rounded-lg px-4 py-3">
              Couldn&apos;t load projects or users.{' '}
              <button type="button" onClick={loadLookups} className="underline font-medium">
                Retry
              </button>
            </div>
          )}

          {/* Title */}
          <div className="space-y-1.5">
            <Label htmlFor="title">Bug Title *</Label>
            <Input
              id="title"
              name="title"
              placeholder="e.g. Sign in button unresponsive on Safari"
              value={form.title}
              onChange={handleChange}
              disabled={isLoading}
            />
            {errors.title && <p className="text-red-500 text-xs">{errors.title}</p>}
          </div>

          {/* Description */}
          <div className="space-y-1.5">
            <Label htmlFor="description">Description *</Label>
            <textarea
              id="description"
              name="description"
              rows={4}
              placeholder="What went wrong, and what did you expect to happen instead?"
              value={form.description}
              onChange={handleChange}
              disabled={isLoading}
              className="w-full px-3 py-2 text-sm border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-violet-500 resize-none placeholder:text-slate-400"
            />
            {errors.description && <p className="text-red-500 text-xs">{errors.description}</p>}
          </div>

          {/* Steps to reproduce */}
          <div className="space-y-1.5">
            <Label htmlFor="stepsToReproduce">Steps to Reproduce</Label>
            <textarea
              id="stepsToReproduce"
              name="stepsToReproduce"
              rows={3}
              placeholder={'1. Go to ...\n2. Click ...\n3. Observe ...'}
              value={form.stepsToReproduce}
              onChange={handleChange}
              disabled={isLoading}
              className="w-full px-3 py-2 text-sm border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-violet-500 resize-none placeholder:text-slate-400"
            />
          </div>

          {/* Project */}
          <div className="space-y-1.5">
            <Label htmlFor="projectId">Project *</Label>
            <select
              id="projectId"
              name="projectId"
              value={form.projectId}
              onChange={handleChange}
              disabled={isLoading}
              className={SELECT}
            >
              <option value="">Select a project...</option>
              {projects.map((p) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
            {errors.projectId && <p className="text-red-500 text-xs">{errors.projectId}</p>}
          </div>

          {/* Severity + Priority */}
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label htmlFor="severity">Severity *</Label>
              <select
                id="severity" name="severity" value={form.severity}
                onChange={handleChange} disabled={isLoading} className={SELECT}
              >
                {BUG_SEVERITIES.map((s) => (
                  <option key={s} value={s}>{BUG_SEVERITY_LABELS[s]}</option>
                ))}
              </select>
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="priority">Priority *</Label>
              <select
                id="priority" name="priority" value={form.priority}
                onChange={handleChange} disabled={isLoading} className={SELECT}
              >
                {BUG_PRIORITIES.map((p) => (
                  <option key={p} value={p}>{BUG_PRIORITY_LABELS[p]}</option>
                ))}
              </select>
            </div>
          </div>

          {/* SLA preview — the commitment this severity creates */}
          {activeRule && (
            <div className="rounded-lg border border-border bg-background px-3 py-2.5">
              <p className="text-xs font-medium text-foreground mb-0.5">
                SLA for {BUG_SEVERITY_LABELS[form.severity]}
              </p>
              <p className="text-xs text-muted-foreground">
                Response within <strong>{formatMinutes(activeRule.responseMinutes)}</strong>
                {' · '}
                Resolution within <strong>{formatMinutes(activeRule.resolutionMinutes)}</strong>
                {' — the clock starts as soon as this bug is filed.'}
              </p>
            </div>
          )}

          {/* Environment + Developer */}
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label htmlFor="environment">Environment</Label>
              <select
                id="environment" name="environment" value={form.environment}
                onChange={handleChange} disabled={isLoading} className={SELECT}
              >
                {BUG_ENVIRONMENTS.map((e) => (
                  <option key={e} value={e}>{BUG_ENVIRONMENT_LABELS[e]}</option>
                ))}
              </select>
            </div>

            {/* Assigning is a triage decision — employees file, managers assign. */}
            {canAssign && (
              <div className="space-y-1.5">
                <Label htmlFor="assigneeId">Developer</Label>
                <select
                  id="assigneeId" name="assigneeId" value={form.assigneeId}
                  onChange={handleChange} disabled={isLoading} className={SELECT}
                >
                  <option value="">Unassigned (triage later)</option>
                  {users.map((u) => (
                    <option key={u.id} value={u.id}>{u.name}</option>
                  ))}
                </select>
              </div>
            )}
          </div>

          {/* Linked task */}
          <div className="space-y-1.5">
            <Label htmlFor="linkedTaskId">Linked Task</Label>
            <select
              id="linkedTaskId" name="linkedTaskId" value={form.linkedTaskId}
              onChange={handleChange}
              disabled={isLoading || !form.projectId || !form.assigneeId}
              className={SELECT}
            >
              <option value="">
                {!form.projectId
                  ? 'Select a project first'
                  : !form.assigneeId
                  ? 'Select a developer first'
                  : 'None'}
              </option>
              {tasks.map((t) => (
                <option key={t.id} value={t.id}>{t.title}</option>
              ))}
            </select>
            <p className="text-xs text-slate-400">
              {form.projectId && form.assigneeId && tasks.length === 0
                ? 'This developer has no tasks in this project. A development task can be created from the bug later.'
                : 'Optional. Only tasks assigned to the chosen developer in this project are listed.'}
            </p>
          </div>

          {/* Attachments */}
          <div className="space-y-1.5">
            <Label htmlFor="attachments">Attachments</Label>
            <input
              id="attachments"
              type="file"
              multiple
              onChange={handleFiles}
              disabled={isLoading}
              accept=".png,.jpg,.jpeg,.pdf,.doc,.docx,.xls,.xlsx,.zip"
              className="w-full text-sm text-muted-foreground file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-sm file:bg-violet-50 file:text-violet-700 hover:file:bg-violet-100"
            />
            <p className="text-xs text-slate-400">
              Screenshots, logs or documents. Up to 10MB each.
            </p>
            {files.length > 0 && (
              <ul className="text-xs text-muted-foreground space-y-0.5 pt-1">
                {files.map((f) => (
                  <li key={f.name}>• {f.name}</li>
                ))}
              </ul>
            )}
            {errors.files && <p className="text-red-500 text-xs">{errors.files}</p>}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-end gap-3 pt-2">
            <Button type="button" variant="outline" onClick={onClose} disabled={isLoading}>
              Cancel
            </Button>
            <Button type="submit" className="bg-violet-600 hover:bg-violet-700" disabled={isLoading}>
              {isLoading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  {uploadPhase || 'Reporting...'}
                </>
              ) : (
                'Report Bug'
              )}
            </Button>
          </div>
        </form>
      </div>
    </div>
  )
}
